### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by alwinhb** [sm7eca/dmr-dreambox#135]
@smangels @sm7eca Does this code contain the implementation of DMR? Tier1 / Tier2?

**Comment by sm7eca** [comment]
Hi, the DMR module is tier 2 and the program handles the setup and operation of two channels. It was some time since we work with the code and I don’t know if the module still available on the market. The command structure is similar to other modules on the market though.

**Comment by alwinhb** [comment]
@sm7eca Thanks for the quick response, I was looking to check if this source code contains DMR protocols implementation.
